[package]
authors = ["Jimseung <lannex.shin@gmail.com>"]
edition = "2018"
name = "tcp-test-server-rust"
version = "0.1.0"

[dependencies]
dotenv = "0.15.0"
encoding_rs = "0.8.23"
hex = "0.4.2"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
